oracle:
  image: oracle

solr:
  image: lukeyoungblood/solr:v0.1.0
  volume_driver: convoy-nfs
  volumes:
    - mysolr-nfs2:/opt/solr/server/solr/cores

hybris:
  image: lukeyoungblood/hybris:v0.1.0
  environment:
    - y_tomcat_http_port:80
    - y_tomcat_ssl_port:443
    - TOMCAT_SERVER_XML:server_proxy_nossl.xml
    - TC_HTTP_PROXY_PORT:80
    - TC_HTTP_REDIRECT_PORT:443
    - TC_HTTPS_PROXY_PORT:443
  env_file:
    - ./acc_env
  volume_driver: convoy-nfs
  volumes:
    - mymedia-nfs2:/etc/hybris/data/media
  depends_on:
    - solr
    - oracle
  links:
    - solr
    - oracle

#lb:
#  labels:
#    io.rancher.scheduler.global: 'true'
#    io.rancher.loadbalancer.ssl.ports: '443'
#  image: rancher/load-balancer-service
#  links:
#    - hybris
#  ports:
#    - 80:9001
#    - 443:9002

#mysql:
#  image: lukeyoungblood/mysql
#  volume_driver: convoy-nfs
#  volumes:
#    - mymysql-nfs2:/opt/hybris/mysql/lib

