.catalog:
  name: "SAP Hybris"
  version: "v0.1.0"
  description: "SAP Hybris B2B eCommerce Platform"
  uuid: Hybris-0
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: db_hostname
      description: "Hostname of your Oracle database server:"
      label: "DB Hostname"
      required: true
      default: "ocs-1233.oc.mckesson.com"
      type: "str"

oracle:
  hostname: ${db_hostname}

hybris:
